CREATE DATABASE IF NOT EXISTS study_in_china DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE study_in_china;

CREATE TABLE IF NOT EXISTS programs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    program_name_cn VARCHAR(300) NOT NULL,
    program_name_en VARCHAR(300) NOT NULL,
    degree_level VARCHAR(50) NOT NULL,
    major_category VARCHAR(100),
    major_cn VARCHAR(200) NOT NULL,
    major_en VARCHAR(200) NOT NULL,
    department_cn VARCHAR(200),
    campus VARCHAR(200),
    description TEXT,
    uni_name_cn VARCHAR(200) NOT NULL,
    uni_name_en VARCHAR(200) NOT NULL,
    uni_short_cn VARCHAR(50),
    uni_city VARCHAR(50),
    uni_province VARCHAR(50),
    uni_region VARCHAR(50),
    uni_type VARCHAR(50),
    uni_tier VARCHAR(100),
    uni_qs_rank INT,
    uni_has_gym TINYINT(1),
    uni_has_pool TINYINT(1),
    uni_english_program_count INT,
    uni_international_student_count INT,
    teaching_language VARCHAR(50),
    duration_years DECIMAL(3,1),
    tuition_currency VARCHAR(10) DEFAULT 'CNY',
    tuition_amount DECIMAL(10,2),
    tuition_period VARCHAR(20) DEFAULT 'per year',
    hsk_requirement VARCHAR(50),
    english_requirement VARCHAR(100),
    dormitory_available TINYINT(1),
    dormitory_type VARCHAR(200),
    halal_canteen_available TINYINT(1) DEFAULT 0,
    prayer_room_available TINYINT(1) DEFAULT 0,
    airport_pickup TINYINT(1),
    scholarship_type VARCHAR(300),
    scholarship_coverage VARCHAR(200),
    application_deadline DATE,
    intake_season VARCHAR(20),
    year_of_admission YEAR,
    is_active TINYINT(1) DEFAULT 1,
    is_manually_verified TINYINT(1) DEFAULT 0,
    data_source VARCHAR(100),
    feature_tags JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_degree (degree_level),
    INDEX idx_major (major_cn),
    INDEX idx_uni (uni_name_cn),
    INDEX idx_city (uni_city)
);

CREATE TABLE IF NOT EXISTS leads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(200),
    phone VARCHAR(50),
    nationality VARCHAR(100),
    current_education VARCHAR(100),
    gpa VARCHAR(20),
    language_level VARCHAR(100),
    budget_range VARCHAR(100),
    interested_major VARCHAR(200),
    interested_degree VARCHAR(50),
    target_city VARCHAR(100),
    source_page VARCHAR(500),
    message TEXT,
    status VARCHAR(20) DEFAULT 'new',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_status (status)
);

INSERT INTO programs (program_name_cn, program_name_en, degree_level, major_category, major_cn, major_en,
                      department_cn, campus, description,
                      uni_name_cn, uni_name_en, uni_short_cn, uni_city, uni_province, uni_region, uni_type, uni_tier,
                      uni_qs_rank, uni_has_gym, uni_has_pool, uni_english_program_count, uni_international_student_count,
                      teaching_language, duration_years, tuition_amount, hsk_requirement, english_requirement,
                      halal_canteen_available, prayer_room_available, dormitory_available,
                      scholarship_type, application_deadline, intake_season, year_of_admission, is_active, data_source)
VALUES
('计算机科学与技术硕士', 'Computer Science Master', '硕士', '工学', '计算机科学与技术', 'Computer Science',
 '计算机学院', '主校区', '培养具备扎实理论基础和工程能力的高级计算机人才。',
 '郑州大学', 'Zhengzhou University', '郑大', '郑州市', '河南', '华中', '综合', '双一流,211',
 551, 1, 1, 15, 2700,
 '英文', 2.0, 35000, '无', '雅思6.0/托福80',
 1, 1, 1,
 '中国政府奖学金,河南省政府奖学金', '2026-06-30', 'Fall', 2026, 1, '测试数据'),
('临床医学本科', 'MBBS', '本科', '医学', '临床医学', 'Clinical Medicine',
 '医学院', '主校区', '六年制英文授课临床医学项目。',
 '郑州大学', 'Zhengzhou University', '郑大', '郑州市', '河南', '华中', '综合', '双一流,211',
 551, 1, 0, 10, 2700,
 '英文', 6.0, 35000, '无', '雅思6.0/托福75',
 1, 0, 1,
 '河南省政府奖学金', '2026-07-15', 'Fall', 2026, 1, '测试数据'),
('英语本科', 'English Bachelor', '本科', '文学', '英语', 'English',
 '英语学院', '主校区', '英语语言文学专业。',
 '浙江外国语学院', 'Zhejiang International Studies University', '浙外', '杭州市', '浙江', '华东', '语言/师范', '省属重点',
 NULL, 1, 0, 8, 400,
 '中文', 4.0, 16000, 'HSK4≥180', '雅思6.0/托福80',
 0, 0, 1,
 '浙江省政府奖学金', '2026-06-30', 'Fall', 2026, 1, '测试数据'),
('软件工程本科', 'Software Engineering Bachelor', '本科', '工学', '软件工程', 'Software Engineering',
 '信息工程学院', '新校区', '全英文授课软件工程。',
 '郑州大学', 'Zhengzhou University', '郑大', '郑州市', '河南', '华中', '综合', '双一流,211',
 551, 1, 1, 15, 2700,
 '英文', 4.0, 25000, '无', '雅思6.0/托福80',
 1, 1, 1,
 '河南省政府奖学金', '2026-06-30', 'Fall', 2026, 1, '测试数据'),
('旅游管理本科', 'Tourism Management Bachelor', '本科', '管理学', '旅游管理', 'Tourism Management',
 '旅游管理学院', '主校区', '旅游管理与服务。',
 '浙江外国语学院', 'Zhejiang International Studies University', '浙外', '杭州市', '浙江', '华东', '语言/师范', '省属重点',
 NULL, 0, 0, 3, 400,
 '中文', 4.0, 16000, 'HSK4≥180', '无',
 0, 0, 1,
 '浙江省政府奖学金', '2026-06-30', 'Fall', 2026, 1, '测试数据');
